blog_pro/account/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from .forms import LoginForm
from . import views

login_form = LoginForm()

app_name = "account"

urlpatterns = [
    # login相关
    url(r"^login$", views.login_view, name="login"),
    url(r"^dj-login1$", auth_views.login, name="dj-login1"),   # 使用内置的登录功能, 其模板是在registration/login.html
    url(r"^dj-login2$", auth_views.login, {"template_name": "self_account/account.html"}, name="dj-login2"),   # 自定义template所在位置

    # logout相关
    url(r"^dj-logout$", auth_views.logout, {"template_name": "self_account/logout.html"}, name="dj-logout"),   # 自定义template所在位置

    # register相关
    url(r"^register$", views.register_view2, name="register"),

    # 修改密码
    # 这里如果指定的话, 会使用默认的template_name, 为registration/password_change_...
    url(r"^change-pass$", auth_views.password_change, 
                        {"template_name": "self_account/password_change_form.html",
                         "post_change_redirect": "/account/change-pass-done"},   # 这是url, 解决 Reverse for 'password_change_done' not found
                        name="change_pass"),
    url(r"^change-pass-done$", auth_views.password_change_done, 
                            {"template_name": "self_account/password_change_done.html"}, 
                            name="change_pass_done"),

    # 密码重置相关, 4个方法 , 5个模板
    url(r"^password-reset$", auth_views.password_reset, 
                             {"template_name": "self_account/password_reset_form.html",           # 设置重设表单模板
                              "email_template_name": "self_account/password_reset_email.html",    # 设置email内容模板
                              "subject_template_name": "self_account/password_reset_subject.txt", # 该文件中的内容就是邮件发送的主题
                              "post_reset_redirect": "/account/password-reset-done"               # 这是url, 成功时重定向到下一个地址
                             },
                             name="password_reset"),
    url(r"^password-reset-done$", auth_views.password_reset_done,
                                 {"template_name":"self_account/password_reset_done.html"},   # 设置完成邮件发送时的重定向到的模板
                                 name="password_reset_done"),
    url(r"^password-reset-comfirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$", auth_views.password_reset_confirm,
                                                                           {"template_name": "self_account/password_reset_confirm",     # 设置确认邮件模板
                                                                            "post_reset_redirect": "/account/password-reset-complete"}, # 这是url, 成功后重定向地址
                                                                            name="password_reset_confirm"),
    url(r"^password-reset-complete$", auth_views.password_reset_complete, 
                                      {"template_name": "self_account/password_reset_complete"},   # 设置完成重置密码后使用模板
                                      name="password_reset_complete"),
    
    # 用户信息相关
    url(r"^my-information$", views.myself, name="my_information"),   # 显示信息
    url(r"^edit-my-information$", views.myself_edit, name="edit_my_information"),   # 可编辑的信息显示

    # 用户上传自己的图片
    url(r"^my-image$", views.my_image, name="my_image"),
]

blog_pro/blog/urls.py
from django.conf.urls import url
from blog.views import index_view, blog_content_view


app_name = "blog"

urlpatterns = [
    url(r"^$", index_view, name="index_blog"),
    url(r"^index$", index_view),

    url(r"^blog/(?P<blog_id>\d)$", blog_content_view),
]

blog_pro/blog_pro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # index页
    url(r"^", include("blog.urls", namespace="blog")),

    # 用户页
    url(r"^account/", include("account.urls", namespace="account")),
    # 密码重置的第三方应用
    url(r"^pwd_reset/", include("password_reset.urls", namespace="pwd_reset", app_name="pwd_reset")),

    # 文章栏目
    url(r"^article/", include("article.urls", namespace="article")),
]

blog_pro/account/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    """User 的oneToOne关联表, 提供额外的一些信息"""
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return "userprofile: {}".format(self.user)   # 使用关联表User中的字段


class UserInfo(models.Model):
    """User 的关联表, 提供用户的详细信息"""
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    school = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100, blank=True)
    profession = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    aboutme = models.TextField(blank=True)
    photo = models.ImageField(blank=True)

    def __str__(self):
        return "userinfo: {}".format(self.user)

blog_pro/account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile, UserInfo

class LoginForm(forms.Form):
    """登录用的表单"""
    username = forms.CharField(label="用户名:")
    password = forms.CharField(label="用户密码:", widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):                                       # 使用ModelForm, 将表单直接与model关联
    """用户更改密码的表单"""
    password = forms.CharField(label="用户密码:", widget=forms.PasswordInput)   # 新增的表单列 
    password2 = forms.CharField(label="确认密码:", widget=forms.PasswordInput)  # 新增的表单列

    class Meta:
        model = User                                                           # 本表单类所使用的数据模型, 及User数据表
        fields = ("username", "email")                                         # 选用的数据表字段, 也可用exclude列表说明
    
    def clean_password2(self):                                                 # 判断是否两次密码相等, 去人输入正误, 直接将方法写入表单
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Password don't match.")
        return cd["password2"]


class UserProfileForm(forms.ModelForm):
    """UserProfile对应的表单"""
    class Meta:
        model = UserProfile
        fields = ("phone", "birth")


class UserInfoForm(forms.ModelForm):
    """UserInfo对应的表单"""
    class Meta:
        model = UserInfo
        fields = ("school", "company", "profession", "address", "aboutme", "photo")
    
    def get(self, a):
        return "我看看这个get是在哪调用的.%s" %a


class UserForm(forms.ModelForm):
    """User主表对应的表单类"""
    class Meta:
        model = User
        fields = ("email",)

blog_pro/account/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from .models import User, UserProfile, UserInfo
from .forms import LoginForm, RegistrationForm, UserForm, UserProfileForm, UserInfoForm


# Create your views here.
def login_view(request):
    """自定义登录功能"""
    if request.method == "POST":
        login_form = LoginForm(request.POST)   # 直接使用Form接收POST中的字典数据
        if login_form.is_valid():   # 判断数据有效性
            cd = login_form.cleaned_data   # 获取有效数据
            user = authenticate(username=cd["username"], password=cd["password"])   # 鉴定是否存在User, 存在返回对象, 不存在返回None

            if user:
                login(request, user)   # 在request中留下一个用户id, 让通过验证的用户可以不用重复去验证, 利用session
                return HttpResponse("Welcome You, authenticated successfully.")
            else:
                return HttpResponse("Invalid login request.")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "self_account/account.html", {"form_obj": login_form})


def register_view(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)                    # 调用ModelForm对象的save方法, 将直接把内容提交至数据库, 这里设置为False
            new_user.set_password(user_form.cleaned_data["password"])  # 设置了对象密码(未检验的)
            new_user.save()                                            # 在次保存, 这下将数据保存至数据库了.
            return HttpResponse("regist successfully.")
        else:
            return HttpResponse("regist fialed.")
    if request.method == "GET":
        user_form = RegistrationForm()
        return render(request, "self_account/register.html", {"form": user_form})   # 用Get方式请求, 则将注册页面返回, 注意form的传递


def register_view2(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)

        if user_form.is_valid() * userprofile_form.is_valid():
            print("所获得的有效数据", user_form.cleaned_data, userprofile_form.cleaned_data)
        # 对User填入数据
            new_user = user_form.save(commit=False)                    
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
        # 对userprofile填入数据
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            # UserInfo.objects.create(user=new_user)
            return HttpResponse("regist successfully.")
        else:
            return HttpResponse("regist fialed.")
    if request.method == "GET":
        user_form = RegistrationForm()
        userprofile_form = UserProfileForm()
        return render(request, "self_account/register.html", {"form": user_form, "profile": userprofile_form})   # 用Get方式请求, 则将注册页面返回, 注意form的传递


@login_required(login_url="/account/login")   # 没有登录的用户会被转到该url
def myself(request):
# 查询出当前用户的相应信息
    user        = User.objects.get(username=request.user.username)
    userprofile = UserProfile.objects.filter(user=user)
    userinfo    = UserInfo.objects.filter(user=user)

    return render(request, "self_account/myself.html", locals())


@login_required(login_url='/account/login/')
def myself_edit(request):
# 查询对应数据库中的相应数据
    user = User.objects.get(username=request.user.username) 
    userprofile = UserProfile.objects.get(user=request.user)
    userinfo = UserInfo.objects.get(user=request.user)

    if request.method == "POST":
    # POST方法用于提交修改, 获取表单request.POST中的数据
        user_form = UserForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        userinfo_form = UserInfoForm(request.POST)

        if user_form.is_valid() * userprofile_form.is_valid() * userinfo_form.is_valid():
        # 获取干净数据
            user_cd = user_form.cleaned_data
            userprofile_cd = userprofile_form.cleaned_data
            userinfo_cd = userinfo_form.cleaned_data
        # 将新数据写入
            user.email = user_cd['email']
            userprofile.birth = userprofile_cd['birth']
            userprofile.phone = userprofile_cd['phone']
            userinfo.school = userinfo_cd['school']
            userinfo.company = userinfo_cd['company']
            userinfo.profession = userinfo_cd['profession']
            userinfo.address = userinfo_cd['address']
            userinfo.aboutme = userinfo_cd['aboutme']
        # 存入数据库
            user.save()
            userprofile.save()
            userinfo.save()
        return HttpResponseRedirect('/account/my-information/')   
    else:
    # 实例化模型表单对象, 并给与对应的初值
        user_form = UserForm(instance=request.user)
        userprofile_form = UserProfileForm(
                initial={"birth":userprofile.birth, "phone":userprofile.phone}
            )
        userinfo_form = UserInfoForm(
                initial={"school":userinfo.school, "company":userinfo.company, 
                         "profession":userinfo.profession, "address":userinfo.address, 
                         "aboutme":userinfo.aboutme}
            )
        return render(request, "self_account/myself_edit.html", 
                     {"user_form":user_form, "userprofile_form":userprofile_form, "userinfo_form":userinfo_form})


def my_image(request):
    """用户图片的处理视图"""
    if request.method == "POST":
        img = request.POST["img"]
        userinfo= UserInfo.objects.get(user=request.user.id)
        userinfo.photo = img
        userinfo.save()
        return HttpResponse("1")
    else:
        return render(request, "self_account/imagecrop.html")

blog_pro/templates/self_account/account.html
{% extends "basement.html" %}
{% load static %}

{% block html_title %}login us{% endblock %}

{% block html_style_link %}
    {% static "CSS/account.css" %}
{% endblock %}

{% block html_body %}
    <h3>Login us</h3>
    <form action="/account/login" method="post">
        {% csrf_token %}
        {{ form_obj.as_p }}
        {% if form_obj is None %}
            {{ form.as_p }}
        {% endif %}

        <input type="submit" value="login in">

        {% comment "使用手动的方式创建表单控件内容" %}
            {% for field in form_obj %}
                <p>{{ field.label }}: {{ field }}</p>
            {% endfor %}
        {% endcomment %}
    </form>
    <p>forgot your password? <a href="{% url "pwd_reset:password_reset_recover" %}">reset password</a></p>
    <p>don't have account? <a href="{% url "account:register" %}"> regist us</a></p>
    <a href="http://www.bootcss.com/">一个资源网站</a>
{% endblock %}

blog_pro/templates/self_account/imagecrop.html
{% load static %}
<link rel="stylesheet" href="{% static "CSS/imagecrop.css" %}" type="text/css" />
</head>
<body>
<script type="text/javascript" src="{% static "JS/jquery-1.11.1.min.js" %}"></script> 
<script type="text/javascript" src="{% static "JS/cropbox-min.js" %}"></script>
<script type="text/javascript" src="{% static "JS/csrf.js" %}"></script>

<div class="container">
  <div class="imageBox">
    <div class="thumbBox"></div>
    <div class="spinner" style="display: none"></div>
  </div>
  <div class="action"> 
    <!-- <input type="file" id="file" style=" width: 200px">-->
    <div class="new-contentarea tc"> <a href="javascript:void(0)" class="upload-img">
      <label for="upload-file">请先选择图片...</label>
      </a>
      <input type="file" class="" name="upload-file" id="upload-file" />
    </div>
    <input type="button"   class="Btnsty_peyton" value="OK">
    <input type="button" id="btnZoomIn" class="Btnsty_peyton" value="+"  >
    <input type="button" id="btnZoomOut" class="Btnsty_peyton" value="-" >
  </div>
  <div class="cropped"></div>
</div>

<script type="text/javascript">
$(window).load(function() {
	//$('#btnCrop').click();$("#idName").css("cssText","background-color:red!important");
	
	//$(".imageBox").css("cssText","background-position:88px 88px!important");$(".imageBox").css("cssText","background-size:222px 222px!important");
	var options =
	{
		thumbBox: '.thumbBox',
		spinner: '.spinner',
		imgSrc: ''
	}
	var cropper = $('.imageBox').cropbox(options);
	var img="";
	$('#upload-file').on('change', function(){
		var reader = new FileReader();
		reader.onload = function(e) {
			options.imgSrc = e.target.result;
			cropper = $('.imageBox').cropbox(options);
			getImg();
		}
		reader.readAsDataURL(this.files[0]);
		this.files = [];
		//getImg();
	})
	$('#btnCrop').on('click', function(){
		alert("图片上传中...");
		// 使用ajax异步将文件传给服务器
		$.ajax({
			url: '{% url "account:my_image" %}',
			type: 'POST',
			data: {"img": img},
			success: function(e){
				location.href="{% url 'account:my_information' %}"
			}
		})
		// return HttpResponse("1")
		if (e=="1"){
			parent.location.reload()
		} else {
			alert("图片上传失败.")
		}
	})
	function getImg(){
		img = cropper.getDataURL();
		$('.cropped').html('');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:180px;margin-top:4px;border-radius:180px;box-shadow:0px 0px 12px #7E7E7E;"><p>180px*180px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:128px;margin-top:4px;border-radius:128px;box-shadow:0px 0px 12px #7E7E7E;"><p>128px*128px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:64px;margin-top:4px;border-radius:64px;box-shadow:0px 0px 12px #7E7E7E;" ><p>64px*64px</p>');
		}
		
	$(".imageBox").on("mouseup",function(){
 		getImg();
  		});
		
		
	$('#btnZoomIn').on('click', function(){
		cropper.zoomIn();
	})
	$('#btnZoomOut').on('click', function(){
		cropper.zoomOut();
	})
});
</script>
</body>
</html>

blog_pro/templates/self_account/logout.html
{% extends "basement.html" %}

{% block html_title %}Logout{% endblock %}

{% block html_body %}
    <p>You have logouted.</p>
    <p>You can <a href="{% url "account:login" %}">login</a> again, or return to <a href="{% url "blog:index_blog" %}">blog</a>.</p>

{% endblock %}

blog_pro/templates/self_account/myself.html
{% extends "basement.html" %}
{% load static %}

{% block html_title %}My Information{% endblock %}

{% block html_style_link %}{% static "CSS/myself.css" %}{% endblock %}

{% block html_body %}
    <h3>My Information</h3>
    {% if userinfo.photo %}
        <p><img src="{{ userinfo.photo | striptags }}"></p>
    {% else %}
        <p><img name="user_face" src="{% static "IM/default_study.jpg" %}"></p>
    {% endif %}
        
    <button id="upload_image" onclick="upload_image_layer()">upload my photo</button>
    <ul>
        <li>用户名: {{ user.username }}</li>
        <li>邮箱: {{ user.email }}</li>
        <li>birth: {{ userprofile.birth }}</li>
        <li>phone: {{ userprofile.phone }}</li>
        <li>曾在学校: {{ userinfo.school }}</li>
        <li>工作单位: {{ userinfo.company }}</li>
        <li>职业: {{ userinfo.profession }}</li>
        <li>地址: {{ userinfo.address }}</li>
        <li>个人介绍: {{ userinfo.aboutme }}</li>
    </ul>
    <a href="{% url "account:edit_my_information" %}">click here to edit my information</a> 

<script type="text/javascript" src="{% static "JS/layer.js" %}"></script>
<script type="text/javascript" src="{% static "JS/jquery-1.11.1.min.js" %}"></script>
<script>
    function upload_image_layer(){
        layer.open({
            title: "上传头像",
            area: ["650px", "650px"],
            type: 2,
            content: "{% url 'account:my_image' %}",
        })
    }
</script>
{% endblock %}

blog_pro/templates/self_account/myself_edit.html
{% extends "basement.html" %}

{% load static %}

{% block html_title %}Edit myself information{% endblock %}
{% block html_style_link %}{% static "CSS/myself.css" %}{% endblock %}

{% block html_body %}
<form action="." method="post">
    {% csrf_token %}
    <ul>
        <li>用户名: {{ user.username }}</li>
        <li>邮箱: {{ user_form.email }}</li>
        <li>birth: {{ userprofile_form.birth }}</li>
        <li>phone: {{ userprofile_form.phone }}</li>
        <li>曾在学校: {{ userinfo_form.school }}</li>
        <li>工作单位: {{ userinfo_form.company }}</li>
        <li>职业: {{ userinfo_form.profession }}</li>
        <li>地址: {{ userinfo_form.address }}</li>
        <li>个人介绍: {{ userinfo_form.aboutme }}</li>
    </ul>
    <input type="submit" value="确认更改">
</form>
{% endblock %}

blog_pro/templates/self_account/password_change_done.html
{% extends "basement.html" %}

{% block html_title %}change password done{% endblock %}

{% block html_body %}
    <h3>You password had changed.</h3>
    <p><a href="{% url "account:login" %}"></a></p>
{% endblock %}

blog_pro/templates/self_account/password_change_form.html
{% extends "basement.html" %}

{% block html_title %}change password{% endblock %}

{% block html_body %}
    <h2>change password</h2>
    <p>please enter your old password and then input the new one.</p>
    {% if form.new_password1.help_text %}
        <p>{{ from.new_password1.help_text|safe }}</p>
    {% endif %}

    <form action="." method="post">
        {% csrf_token %}
        <p>{{ form.old_password.label_tag }} {{ form.old_password }}</p>
        <p>{{ form.new_password1.label_tag }} {{ form.new_password1 }}</p>
        <p>{{ form.new_password2.label_tag }} {{ form.new_password2 }}</p>
        <input type="submit" value="confirm">
    </form>
{% endblock %}

blog_pro/templates/self_account/password_reset_complete.html
{% extends "basement.html" %}

{% block html_title %}Reset Done{% endblock %}

{% block html_body %}
    <p>Your password has been set.</p>
    <p>Click here to <a href="{% url "account:login" %}">login</a></p>
{% endblock %}

blog_pro/templates/self_account/password_reset_confirm.html
{% extends "basement.html" %}

{% block html_title %}Reset Password{% endblock %}

{% block html_body %}
    <h3>Reset Password</h3>
    <p>{{ form.new_password1 }}</p>
    <p>{{ form.new_password2 }}</p>
    <input type="submit" value="confirm Password">
{% endblock %}

blog_pro/templates/self_account/password_reset_done.html
{% extends "basement.html" %}

{% block html_title %}password reset{% endblock %}

{% block html_body %}
    <h3>Email have send.</h3>
    <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock %}

blog_pro/templates/self_account/password_reset_email.html
<p>您在网站上请求了重置密码, 如果非本人操作, 请不要回复.</p>
{{ protocol }}://{{ domain }}{% url "account:password_reset_confirm" uidb64=uid token=token %}
<p>你的账号: {{ request.user.username }}</p>

blog_pro/templates/self_account/password_reset_form.html
{% extends "basement.html" %}

{% block html_title %}password reset{% endblock %}

{% block html_body %}
    <h3>If you have forgot your password, you can reset here.</h3>
    <form action="/account/password-reset" method="post">
        {% csrf_token %}
        <p>{{ form.email }}</p>
        <input type="submit" value="send email">
    </form>
{% endblock %}

blog_pro/templates/self_account/register.html
{% extends "basement.html" %}

{% load static %}

{% block html_title %}register yourself{% endblock %}

{% block html_body %}
    <h3>register</h3>
    <form action="{% url "account:register" %}" method="post">
    {% csrf_token %}
    <p>If you have an account, just <a href="{% url "account:login" %}">login us</a></p>
    <p>
        <label for="{{ form.username.id_for_label }}">用户名:</label>
        {{ form.username }}
    </p>
    <p>
        <label for="{{ form.email.id_for_label }}">邮箱</label>
        {{ form.email }}
    </p>
    <p>
        <label for="{{ form.password.id_for_label }}">新建密码:</label>
        {{ form.password }}
    </p>
    <p>
        <label for="{{ form.password2.id_for_label }}">确认密码:</label>
        {{ form.password2 }}
    </p>
    <p>
        <label for="{{ profile.birth.id_for_label }}">出生日期:</label>
        {{ profile.birth }}
    </p>
    <p>
        <label for="{{ profile.phone.id_for_label }}">手机号:</label>
        {{ profile.phone }}
    </p>
    <input type="submit" value="register us">
    </form>
{% endblock %}